### PR TITLE
Option "silent" for location didn't work

### PR DESCRIPTION
**Pull request by h4**
We was needed for silent change location. But it didn't work:

```
location.change({url: 'some url', silent: true});
```

Event "change" was still emitted.

If I pass `{url: 'some url', {data: {silent: true } }` It works, but It looks strange and doesn't match with jsDoc.

### CODE REVIEW

**Comment by tadatuta** [comment]
LGTM, but I'm not quite sure if it's a patch (as it fixes a bug) or major (as it changes API) update

**Comment by h4** [comment]
It isn't changed documented API (see tests). But if someone uses workaround with `{url: 'some url', {data: {silent: true } }` it'll brake his code.

Maybe it has mistake in documentation. But in this case we should change https://github.com/bem/bem-history/blame/v3/common.blocks/location/location.js#L100

**Comment by h4** [comment]
Anyway, I realise that we don't need call `location.change()` in silent mode in our blocks and now we don't depend on this PR  :)

**Comment by tadatuta** [comment]
merged to `v4` branch

**Pull request closed without merging**
